feat: add olm bundle
koor-tech/koor-operator pull request #9
Opened 2023-01-26 04:03 UTC by zalsader

and update documentation

2023-02-01 18:31 UTC, galexrt requested changes

2023-02-01 19:45 UTC, zalsader commented on README.md
>  sudo docker run -d --network=host alpine/socat TCP-LISTEN:5000,reuseaddr,fork TCP:$(minikube ip):5000
This `socat` command only exposes minikube's registry to the host: https://minikube.sigs.k8s.io/docs/handbook/registry/#docker-on-macos

2023-02-03 11:01 UTC, galexrt approved these changes
Commit lint is currently complaining but besides that LGTM

2023-02-03 18:40 UTC, galexrt approved these changes

2023-02-03 18:42 UTC, merged